-- 코드를 입력하세요
SELECT outs.ANIMAL_ID, outs.ANIMAL_TYPE, outs.NAME
FROM ANIMAL_INS ins JOIN ANIMAL_OUTS outs ON ins.ANIMAL_ID = outs.ANIMAL_ID
WHERE ins.SEX_UPON_INTAKE LIKE 'intact%' AND outs.SEX_UPON_OUTCOME NOT LIKE 'intact%'
ORDER BY outs.ANIMAL_ID