-- 코드를 입력하세요
# 리뷰를 가장 많이 작성한 회원의 리뷰들을 조회
SELECT p.MEMBER_NAME, r.REVIEW_TEXT, DATE_FORMAT(r.REVIEW_DATE, '%Y-%m-%d') as REVIEW_DATE
FROM MEMBER_PROFILE p JOIN REST_REVIEW r ON p.MEMBER_ID = r.MEMBER_ID
WHERE (p.MEMBER_ID) = (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY COUNT(REVIEW_TEXT) DESC
    LIMIT 1
    )
ORDER BY p.MEMBER_NAME, r.REVIEW_DATE, r.REVIEW_TEXT