SELECT COUNT(USER_ID) into @user_count FROM USER_INFO WHERE YEAR(JOINED) = 2021;


SELECT YEAR(O.sales_date) AS YEAR,
    MONTH(O.sales_date) AS MONTH,
    count(O.USER_ID) AS PUCHASED_USERS,
    ROUND(count(DISTINCT O.USER_ID)/@user_count,1) AS PUCHASED_RATIO
FROM ONLINE_SALE O
    INNER JOIN USER_INFO U ON U.USER_ID = O.USER_ID AND YEAR(U.JOINED) = 2021
GROUP BY YEAR(O.sales_date),MONTH(O.sales_date)
ORDER BY YEAR,MONTH