-- 코드를 입력하세요
SELECT prod.PRODUCT_ID, prod.PRODUCT_NAME, sum(orders.AMOUNT*prod.PRICE) as TOTAL_SALES
FROM FOOD_PRODUCT prod JOIN FOOD_ORDER orders ON prod.PRODUCT_ID = orders.PRODUCT_ID
WHERE (orders.PRODUCE_DATE) LIKE '2022-05%'
GROUP BY prod.PRODUCT_ID
ORDER BY TOTAL_SALES DESC,prod.PRODUCT_ID