-- 코드를 입력하세요
SELECT HOUR(DATETIME) as h, COUNT(*)
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
    # HAVING HOUR(DATETIME) BETWEEN 9 AND 19
HAVING h BETWEEN 9 AND 19
ORDER BY HOUR(DATETIME)

-- 코드를 입력하세요
SELECT HOUR(DATETIME) as h, COUNT(*)
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
    # HAVING HOUR(DATETIME) BETWEEN 9 AND 19
    # HAVING h BETWEEN 9 AND 19
ORDER BY HOUR(DATETIME)