-- 코드를 입력하세요
#  우유와 요거트를 동시에 구입한 장바구니의 아이디를 조회
SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
) AND NAME = 'Yogurt'
    # GROUP BY CART_ID
ORDER BY CART_ID

-- 코드를 입력하세요
    #  우유와 요거트를 동시에 구입한 장바구니의 아이디를 조회
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk','Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME)=2
ORDER BY CART_ID