-- 코드를 입력하세요
SELECT CAR_ID, ROUND(AVG(DATEDIFF(END_DATE,START_DATE)),1)+1 AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY rental
GROUP BY CAR_ID
# HAVING AVG(END_DATE-START_DATE)>=6 // 숫자 빼기
# HAVING AVG(DATEDIFF(END_DATE,START_DATE)) >= 6
HAVING AVG(DATEDIFF(END_DATE,START_DATE)+1) >= 7
ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC