-- 코드를 입력하세요
SELECT
users.USER_ID,
users.NICKNAME,
CONCAT(CITY,' ',STREET_ADDRESS1,' ', STREET_ADDRESS2) as 전체주소,
CONCAT(SUBSTRING(TLNO,1,3), '-', SUBSTRING(TLNO,4,4), '-', SUBSTRING(TLNO,8)) as 전화번호
FROM USED_GOODS_BOARD as board LEFT JOIN USED_GOODS_USER as users ON board.WRITER_ID = users.USER_ID
GROUP BY board.WRITER_ID
HAVING COUNT(*)>=3
ORDER BY board.WRITER_ID DESC

-- 코드를 입력하세요
SELECT
USER_ID, NICKNAME,
CONCAT(CITY,' ',STREET_ADDRESS1,' ', STREET_ADDRESS2) as 전체주소,
CONCAT(SUBSTRING(TLNO,1,3), '-', SUBSTRING(TLNO,4,4), '-', SUBSTRING(TLNO,8)) as 전화번호
FROM USED_GOODS_BOARD as board JOIN USED_GOODS_USER as users ON board.WRITER_ID = users.USER_ID
GROUP BY board.WRITER_ID
HAVING COUNT(*)>=3
ORDER BY board.WRITER_ID DESC